/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include <openssl/cmperr.h>

#ifndef OPENSSL_NO_ERR

static const ERR_STRING_DATA CMP_str_functs[] = {
    {ERR_PACK(ERR_LIB_CMP, CMP_F_CMP_ASN1_OCTET_STRING_SET1, 0),
     "CMP_ASN1_OCTET_STRING_set1"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_CMP_ASN1_OCTET_STRING_SET1_BYTES, 0),
     "CMP_ASN1_OCTET_STRING_set1_bytes"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_CMP_CTX_SET1_CAPUBS, 0),
     "CMP_CTX_set1_caPubs"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_CMP_CTX_SET1_EXTRACERTSIN, 0),
     "CMP_CTX_set1_extraCertsIn"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_CMP_CTX_SET1_NEWCLCERT, 0),
     "CMP_CTX_set1_newClCert"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_CMP_CTX_SET1_RECIPNONCE, 0),
     "CMP_CTX_set1_recipNonce"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_GENINFO_PUSH0_ITAV, 0),
     "OSSL_CMP_CTX_geninfo_push0_ITAV"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_GENM_PUSH0_ITAV, 0),
     "OSSL_CMP_CTX_genm_push0_ITAV"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_GET1_CAPUBS, 0),
     "OSSL_CMP_CTX_get1_caPubs"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_GET1_EXTRACERTSIN, 0),
     "OSSL_CMP_CTX_get1_extraCertsIn"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_PUSH1_EXTRACERTSOUT, 0),
     "OSSL_CMP_CTX_push1_extraCertsOut"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_PUSH1_POLICYOID, 0),
     "OSSL_CMP_CTX_push1_policyOID"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_PUSH1_SUBJECTALTNAME, 0),
     "OSSL_CMP_CTX_push1_subjectAltName"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_REQEXTENSIONS_HAVE_SAN, 0),
     "OSSL_CMP_CTX_reqExtensions_have_SAN"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET0_NEWPKEY, 0),
     "OSSL_CMP_CTX_set0_newPkey"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET0_PKEY, 0),
     "OSSL_CMP_CTX_set0_pkey"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET0_REQEXTENSIONS, 0),
     "OSSL_CMP_CTX_set0_reqExtensions"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_CLCERT, 0),
     "OSSL_CMP_CTX_set1_clCert"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_EXPECTED_SENDER, 0),
     "OSSL_CMP_CTX_set1_expected_sender"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_EXTRACERTSOUT, 0),
     "OSSL_CMP_CTX_set1_extraCertsOut"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_ISSUER, 0),
     "OSSL_CMP_CTX_set1_issuer"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_LAST_SENDERNONCE, 0),
     "OSSL_CMP_CTX_set1_last_senderNonce"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_OLDCLCERT, 0),
     "OSSL_CMP_CTX_set1_oldClCert"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_P10CSR, 0),
     "OSSL_CMP_CTX_set1_p10CSR"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_PROXYNAME, 0),
     "OSSL_CMP_CTX_set1_proxyName"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_RECIPIENT, 0),
     "OSSL_CMP_CTX_set1_recipient"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_REFERENCEVALUE, 0),
     "OSSL_CMP_CTX_set1_referenceValue"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_REQEXTENSIONS, 0),
     "OSSL_CMP_CTX_set1_reqExtensions"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_SECRETVALUE, 0),
     "OSSL_CMP_CTX_set1_secretValue"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_SERVERNAME, 0),
     "OSSL_CMP_CTX_set1_serverName"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_SERVERPATH, 0),
     "OSSL_CMP_CTX_set1_serverPath"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_SRVCERT, 0),
     "OSSL_CMP_CTX_set1_srvCert"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_SUBJECTNAME, 0),
     "OSSL_CMP_CTX_set1_subjectName"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET1_TRANSACTIONID, 0),
     "OSSL_CMP_CTX_set1_transactionID"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET_OPTION, 0),
     "OSSL_CMP_CTX_set_option"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET_PROXYPORT, 0),
     "OSSL_CMP_CTX_set_proxyPort"},
    {ERR_PACK(ERR_LIB_CMP, CMP_F_OSSL_CMP_CTX_SET_SERVERPORT, 0),
     "OSSL_CMP_CTX_set_serverPort"},
    {0, NULL}
};

static const ERR_STRING_DATA CMP_str_reasons[] = {
    {ERR_PACK(ERR_LIB_CMP, 0, CMP_R_INVALID_ARGS), "invalid args"},
    {ERR_PACK(ERR_LIB_CMP, 0, CMP_R_MULTIPLE_SAN_SOURCES),
    "multiple san sources"},
    {ERR_PACK(ERR_LIB_CMP, 0, CMP_R_NULL_ARGUMENT), "null argument"},
    {0, NULL}
};

#endif

int ERR_load_CMP_strings(void)
{
#ifndef OPENSSL_NO_ERR
    if (ERR_func_error_string(CMP_str_functs[0].error) == NULL) {
        ERR_load_strings_const(CMP_str_functs);
        ERR_load_strings_const(CMP_str_reasons);
    }
#endif
    return 1;
}
