/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_CMPERR_H
# define HEADER_CMPERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_CMP

#  ifdef  __cplusplus
extern "C"
#  endif
int ERR_load_CMP_strings(void);

/*
 * CMP function codes.
 */
#  define CMP_F_ADD_EXTENSION                              100
#  define CMP_F_CMP_CALC_PROTECTION                        101
#  define CMP_F_CMP_CERTREPMESSAGE_GET0_CERTRESPONSE       102
#  define CMP_F_CMP_CERTRESPONSE_GET_CERTIFICATE           103
#  define CMP_F_CMP_CERTSTATUS_SET_CERTHASH                104
#  define CMP_F_CMP_CTX_SET1_CAPUBS                        105
#  define CMP_F_CMP_CTX_SET1_EXTRACERTSIN                  106
#  define CMP_F_CMP_CTX_SET1_NEWCLCERT                     107
#  define CMP_F_CMP_CTX_SET1_RECIPNONCE                    108
#  define CMP_F_CMP_EXCHANGE_CERTCONF                      109
#  define CMP_F_CMP_EXCHANGE_ERROR                         110
#  define CMP_F_CMP_GEN_NEW                                111
#  define CMP_F_CMP_PKIFREETEXT_PUSH_STR                   112
#  define CMP_F_CMP_PKISI_PKISTATUS_GET_STRING             113
#  define CMP_F_CMP_POLLREPCONTENT_GET0_POLLREP            114
#  define CMP_F_CMP_REVREPCONTENT_GET_CERTID               115
#  define CMP_F_CMP_REVREPCONTENT_GET_PKISTATUSINFO        116
#  define CMP_F_CMP_VERIFY_PBMAC                           117
#  define CMP_F_CMP_VERIFY_POPO                            118
#  define CMP_F_CMP_VERIFY_SIGNATURE                       119
#  define CMP_F_CRM_NEW                                    120
#  define CMP_F_FIND_SRVCERT                               121
#  define CMP_F_GET_CERT_STATUS                            122
#  define CMP_F_CMP_ASN1_OCTET_STRING_SET1                 123
#  define CMP_F_CMP_ASN1_OCTET_STRING_SET1_BYTES           124
#  define CMP_F_OSSL_CMP_CERTCONF_NEW                      125
#  define CMP_F_OSSL_CMP_CERTREP_NEW                       126
#  define CMP_F_OSSL_CMP_CERTREQ_NEW                       127
#  define CMP_F_OSSL_CMP_CTX_GET1_CAPUBS                   128
#  define CMP_F_OSSL_CMP_CTX_GET1_EXTRACERTSIN             129
#  define CMP_F_OSSL_CMP_CTX_PUSH1_EXTRACERTSOUT           130
#  define CMP_F_OSSL_CMP_CTX_PUSH_FREETEXT                 131
#  define CMP_F_OSSL_CMP_CTX_SET0_NEWPKEY                  132
#  define CMP_F_OSSL_CMP_CTX_SET0_PKEY                     133
#  define CMP_F_OSSL_CMP_CTX_SET0_REQEXTENSIONS            134
#  define CMP_F_OSSL_CMP_CTX_SET1_CLCERT                   135
#  define CMP_F_OSSL_CMP_CTX_SET1_EXPECTED_SENDER          136
#  define CMP_F_OSSL_CMP_CTX_SET1_EXTRACERTSOUT            137
#  define CMP_F_OSSL_CMP_CTX_SET1_ISSUER                   138
#  define CMP_F_OSSL_CMP_CTX_SET1_LAST_SENDERNONCE         139
#  define CMP_F_OSSL_CMP_CTX_SET1_NEWPKEY                  140
#  define CMP_F_OSSL_CMP_CTX_SET1_OLDCLCERT                141
#  define CMP_F_OSSL_CMP_CTX_SET1_P10CSR                   142
#  define CMP_F_OSSL_CMP_CTX_SET1_PKEY                     143
#  define CMP_F_OSSL_CMP_CTX_SET1_PROXYNAME                144
#  define CMP_F_OSSL_CMP_CTX_SET1_RECIPIENT                145
#  define CMP_F_OSSL_CMP_CTX_SET1_REFERENCEVALUE           146
#  define CMP_F_OSSL_CMP_CTX_SET1_SECRETVALUE              147
#  define CMP_F_OSSL_CMP_CTX_SET1_SERVERNAME               148
#  define CMP_F_OSSL_CMP_CTX_SET1_SERVERPATH               149
#  define CMP_F_OSSL_CMP_CTX_SET1_SRVCERT                  150
#  define CMP_F_OSSL_CMP_CTX_SET1_SUBJECTNAME              151
#  define CMP_F_OSSL_CMP_CTX_SET1_TRANSACTIONID            152
#  define CMP_F_OSSL_CMP_CTX_SET_PROXYPORT                 153
#  define CMP_F_OSSL_CMP_CTX_SET_SERVERPORT                154
#  define CMP_F_OSSL_CMP_CTX_PUSH1_SUBJECTALTNAME          155
#  define CMP_F_OSSL_CMP_ERROR_NEW                         156
#  define CMP_F_OSSL_CMP_EXEC_CR_SES                       157
#  define CMP_F_OSSL_CMP_EXEC_GENM_SES                     158
#  define CMP_F_OSSL_CMP_EXEC_IR_SES                       159
#  define CMP_F_OSSL_CMP_EXEC_KUR_SES                      160
#  define CMP_F_OSSL_CMP_EXEC_P10CR_SES                    161
#  define CMP_F_OSSL_CMP_EXEC_RR_SES                       162
#  define CMP_F_OSSL_CMP_HDR_GENERALINFO_PUSH1_ITEMS       163
#  define CMP_F_OSSL_CMP_HDR_GENERALINFO_PUSH0_ITEM        164
#  define CMP_F_OSSL_CMP_HDR_GET_PVNO                      165
#  define CMP_F_OSSL_CMP_HDR_INIT                          166
#  define CMP_F_OSSL_CMP_HDR_PUSH0_FREETEXT                167
#  define CMP_F_OSSL_CMP_HDR_PUSH1_FREETEXT                168
#  define CMP_F_OSSL_CMP_HDR_SET_PVNO                      169
#  define CMP_F_OSSL_CMP_HDR_UPDATE_MESSAGETIME            170
#  define CMP_F_OSSL_CMP_MSG_CHECK_RECEIVED                171
#  define CMP_F_OSSL_CMP_MSG_CREATE                        172
#  define CMP_F_OSSL_CMP_MSG_GEN_PUSH1_ITAVS               173
#  define CMP_F_OSSL_CMP_MSG_GEN_PUSH0_ITAV                174
#  define CMP_F_OSSL_CMP_MSG_HTTP_PERFORM                  175
#  define CMP_F_OSSL_CMP_MSG_PROTECT                       176
#  define CMP_F_OSSL_CMP_PKICONF_NEW                       177
#  define CMP_F_OSSL_CMP_PKISI_GET_PKIFAILUREINFO          178
#  define CMP_F_OSSL_CMP_PKISI_GET_PKISTATUS               179
#  define CMP_F_OSSL_CMP_POLLREP_NEW                       180
#  define CMP_F_OSSL_CMP_POLLREQ_NEW                       181
#  define CMP_F_OSSL_CMP_PRINT_CERT_VERIFY_CB              182
#  define CMP_F_OSSL_CMP_RP_NEW                            183
#  define CMP_F_OSSL_CMP_RR_NEW                            184
#  define CMP_F_OSSL_CMP_STATUSINFO_NEW                    185
#  define CMP_F_OSSL_CMP_VALIDATE_CERT_PATH                186
#  define CMP_F_OSSL_CMP_VALIDATE_MSG                      187
#  define CMP_F_POLLFORRESPONSE                            188
#  define CMP_F_PROCESS_CERTCONF                           189
#  define CMP_F_PROCESS_CERT_REQUEST                       190
#  define CMP_F_PROCESS_ERROR                              191
#  define CMP_F_PROCESS_GENM                               192
#  define CMP_F_PROCESS_POLLREQ                            193
#  define CMP_F_PROCESS_REQUEST                            194
#  define CMP_F_PROCESS_RR                                 195
#  define CMP_F_SAVE_STATUSINFO                            196
#  define CMP_F_SEND_RECEIVE_CHECK                         197
#  define CMP_F_SET1_AOSTR_ELSE_RANDOM                     198
#  define CMP_F_SET1_GENERAL_NAME                          199

/*
 * CMP reason codes.
 */
#  define CMP_R_ALGORITHM_NOT_SUPPORTED                    100
#  define CMP_R_BAD_CHECKAFTER_IN_POLLREP                  101
#  define CMP_R_BAD_REQUEST_ID                             102
#  define CMP_R_CERTID_NOT_FOUND                           103
#  define CMP_R_CERTIFICATE_NOT_ACCEPTED                   104
#  define CMP_R_CERTIFICATE_NOT_FOUND                      105
#  define CMP_R_CERTREQMSG_NOT_FOUND                       106
#  define CMP_R_CERTRESPONSE_NOT_FOUND                     107
#  define CMP_R_CERT_AND_KEY_DO_NOT_MATCH                  108
#  define CMP_R_CONNECT_TIMEOUT                            109
#  define CMP_R_CP_NOT_RECEIVED                            110
#  define CMP_R_ENCOUNTERED_KEYUPDATEWARNING               111
#  define CMP_R_ENCOUNTERED_UNSUPPORTED_PKISTATUS          112
#  define CMP_R_ENCOUNTERED_WAITING                        113
#  define CMP_R_ERROR_CALCULATING_PROTECTION               114
#  define CMP_R_ERROR_CONNECTING                           115
#  define CMP_R_ERROR_CREATING_CERTCONF                    116
#  define CMP_R_ERROR_CREATING_CERTREP                     117
#  define CMP_R_ERROR_CREATING_CR                          118
#  define CMP_R_ERROR_CREATING_ERROR                       119
#  define CMP_R_ERROR_CREATING_GENM                        120
#  define CMP_R_ERROR_CREATING_GENP                        121
#  define CMP_R_ERROR_CREATING_IR                          122
#  define CMP_R_ERROR_CREATING_KUR                         123
#  define CMP_R_ERROR_CREATING_P10CR                       124
#  define CMP_R_ERROR_CREATING_PKICONF                     125
#  define CMP_R_ERROR_CREATING_POLLREP                     126
#  define CMP_R_ERROR_CREATING_POLLREQ                     127
#  define CMP_R_ERROR_CREATING_RP                          128
#  define CMP_R_ERROR_CREATING_RR                          129
#  define CMP_R_ERROR_DECODING_MESSAGE                     130
#  define CMP_R_ERROR_PARSING_PKISTATUS                    131
#  define CMP_R_ERROR_PROCESSING_CERTREQ                   132
#  define CMP_R_ERROR_PROCESSING_MSG                       133
#  define CMP_R_ERROR_PROTECTING_MESSAGE                   134
#  define CMP_R_ERROR_PUSHING_GENERALINFO_ITEM             135
#  define CMP_R_ERROR_PUSHING_GENERALINFO_ITEMS            136
#  define CMP_R_ERROR_SENDING_REQUEST                      138
#  define CMP_R_ERROR_SETTING_CERTHASH                     139
#  define CMP_R_ERROR_TRANSFERRING_IN                      140
#  define CMP_R_ERROR_TRANSFERRING_OUT                     141
#  define CMP_R_ERROR_VALIDATING_PROTECTION                142
#  define CMP_R_FAILED_EXTRACTING_PUBKEY                   143
#  define CMP_R_FAILED_TO_RECEIVE_PKIMESSAGE               144
#  define CMP_R_FAILED_TO_SEND_REQUEST                     145
#  define CMP_R_FAILURE_OBTAINING_RANDOM                   146
#  define CMP_R_FAIL_INFO_OUT_OF_RANGE                     147
#  define CMP_R_GENP_NOT_RECEIVED                          148
#  define CMP_R_INVALID_ARGS                               149
#  define CMP_R_INVALID_PARAMETERS                         150
#  define CMP_R_IP_NOT_RECEIVED                            151
#  define CMP_R_KUP_NOT_RECEIVED                           152
#  define CMP_R_MISSING_KEY_INPUT_FOR_CREATING_PROTECTION  153
#  define CMP_R_MISSING_KEY_USAGE_DIGITALSIGNATURE         154
#  define CMP_R_MISSING_PROTECTION                         155
#  define CMP_R_MULTIPLE_RESPONSES_NOT_SUPPORTED           156
#  define CMP_R_MULTIPLE_SAN_SOURCES                       157
#  define CMP_R_NO_SENDER_NO_REFERENCE                     158
#  define CMP_R_NO_SUITABLE_SERVER_CERT                    159
#  define CMP_R_NO_VALID_SERVER_CERT_FOUND                 160
#  define CMP_R_NULL_ARGUMENT                              161
#  define CMP_R_PKIBODY_ERROR                              162
#  define CMP_R_PKICONF_NOT_RECEIVED                       163
#  define CMP_R_PKISTATUSINFO_NOT_FOUND                    164
#  define CMP_R_POLLREP_NOT_RECEIVED                       165
#  define CMP_R_POTENTIALLY_INVALID_CERTIFICATE            166
#  define CMP_R_READ_TIMEOUT                               167
#  define CMP_R_RECEIVED_ERROR                             168
#  define CMP_R_RECEIVED_NEGATIVE_CHECKAFTER_IN_POLLREP    169
#  define CMP_R_RECIPNONCE_UNMATCHED                       170
#  define CMP_R_REQUEST_NOT_ACCEPTED                       171
#  define CMP_R_REQUEST_REJECTED_BY_CA                     172
#  define CMP_R_RP_NOT_RECEIVED                            173
#  define CMP_R_SENDER_GENERALNAME_TYPE_NOT_SUPPORTED      174
#  define CMP_R_TLS_ERROR                                  175
#  define CMP_R_TOTAL_TIMEOUT                              176
#  define CMP_R_TRANSACTIONID_UNMATCHED                    177
#  define CMP_R_UNEXPECTED_PKIBODY                         178
#  define CMP_R_UNEXPECTED_PKISTATUS                       179
#  define CMP_R_UNEXPECTED_PVNO                            180
#  define CMP_R_UNEXPECTED_REQUEST_ID                      181
#  define CMP_R_UNEXPECTED_SENDER                          182
#  define CMP_R_UNKNOWN_ALGORITHM_ID                       183
#  define CMP_R_UNKNOWN_CERT_TYPE                          184
#  define CMP_R_UNKNOWN_PKISTATUS                          185
#  define CMP_R_UNSUPPORTED_ALGORITHM                      186
#  define CMP_R_UNSUPPORTED_KEY_TYPE                       187
#  define CMP_R_UNSUPPORTED_PROTECTION_ALG_DHBASEDMAC      188
#  define CMP_R_WRONG_ALGORITHM_OID                        189
#  define CMP_R_WRONG_CERTID_IN_RP                         190
#  define CMP_R_WRONG_CERT_HASH                            191
#  define CMP_R_WRONG_PBM_VALUE                            192
#  define CMP_R_WRONG_RP_COMPONENT_COUNT                   193

# endif
#endif
