/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2018 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_CMPERR_H
# define HEADER_CMPERR_H

# ifdef  __cplusplus
extern "C" {
# endif
int ERR_load_CMP_strings(void);
# ifdef  __cplusplus
}
# endif

/*
 * CMP function codes.
 */
# define CMP_F_CMP_CALC_PROTECTION                        176
# define CMP_F_CMP_CALC_PROTECTION_PBMAC                  100
# define CMP_F_CMP_CALC_PROTECTION_SIG                    101
# define CMP_F_CMP_CERTCONF_NEW                           102
# define CMP_F_CMP_CERTORENCCERT_ENCCERT_GET1             103
# define CMP_F_CMP_CERTREPMESSAGE_CERTRESPONSE_GET0       104
# define CMP_F_CMP_CERTREQ_NEW                            105
# define CMP_F_CMP_CERTRESPONSE_GET_CERTIFICATE           106
# define CMP_F_CMP_CERTSTATUS_SET_CERTHASH                107
# define CMP_F_CMP_CTX_CAPUBS_GET1                        108
# define CMP_F_CMP_CTX_CAPUBS_NUM                         109
# define CMP_F_CMP_CTX_CAPUBS_POP                         110
# define CMP_F_CMP_CTX_CREATE                             111
# define CMP_F_CMP_CTX_EXTRACERTSIN_GET1                  112
# define CMP_F_CMP_CTX_EXTRACERTSIN_NUM                   113
# define CMP_F_CMP_CTX_EXTRACERTSIN_POP                   114
# define CMP_F_CMP_CTX_EXTRACERTSOUT_NUM                  115
# define CMP_F_CMP_CTX_EXTRACERTSOUT_PUSH1                116
# define CMP_F_CMP_CTX_INIT                               117
# define CMP_F_CMP_CTX_SET0_NEWPKEY                       118
# define CMP_F_CMP_CTX_SET0_PKEY                          119
# define CMP_F_CMP_CTX_SET0_REQEXTENSIONS                 120
# define CMP_F_CMP_CTX_SET0_TLSBIO                        121
# define CMP_F_CMP_CTX_SET1_CAPUBS                        122
# define CMP_F_CMP_CTX_SET1_CLCERT                        123
# define CMP_F_CMP_CTX_SET1_EXPECTED_SENDER               124
# define CMP_F_CMP_CTX_SET1_EXTRACERTSIN                  125
# define CMP_F_CMP_CTX_SET1_EXTRACERTSOUT                 126
# define CMP_F_CMP_CTX_SET1_ISSUER                        127
# define CMP_F_CMP_CTX_SET1_NEWCLCERT                     128
# define CMP_F_CMP_CTX_SET1_NEWPKEY                       129
# define CMP_F_CMP_CTX_SET1_OLDCLCERT                     130
# define CMP_F_CMP_CTX_SET1_P10CSR                        131
# define CMP_F_CMP_CTX_SET1_PKEY                          132
# define CMP_F_CMP_CTX_SET1_PROXYNAME                     133
# define CMP_F_CMP_CTX_SET1_RECIPIENT                     134
# define CMP_F_CMP_CTX_SET1_RECIPNONCE                    135
# define CMP_F_CMP_CTX_SET1_REFERENCEVALUE                136
# define CMP_F_CMP_CTX_SET1_SECRETVALUE                   137
# define CMP_F_CMP_CTX_SET1_SERVERNAME                    138
# define CMP_F_CMP_CTX_SET1_SERVERPATH                    139
# define CMP_F_CMP_CTX_SET1_SRVCERT                       140
# define CMP_F_CMP_CTX_SET1_SUBJECTNAME                   141
# define CMP_F_CMP_CTX_SET1_TRANSACTIONID                 142
# define CMP_F_CMP_CTX_SET_PROXYPORT                      143
# define CMP_F_CMP_CTX_SET_SERVERPORT                     144
# define CMP_F_CMP_CTX_SUBJECTALTNAME_PUSH1               145
# define CMP_F_CMP_ERROR_NEW                              146
# define CMP_F_CMP_EXEC_CR_SES                            147
# define CMP_F_CMP_EXEC_GENM_SES                          148
# define CMP_F_CMP_EXEC_IR_SES                            149
# define CMP_F_CMP_EXEC_KUR_SES                           150
# define CMP_F_CMP_EXEC_P10CR_SES                         151
# define CMP_F_CMP_EXEC_RR_SES                            152
# define CMP_F_CMP_GENM_NEW                               153
# define CMP_F_CMP_PKIHEADER_GENERALINFO_ITEM_PUSH0       154
# define CMP_F_CMP_PKIHEADER_NEW_SENDERNONCE              174
# define CMP_F_CMP_PKIHEADER_SET1_TRANSACTIONID           175
# define CMP_F_CMP_PKIMESSAGE_GENERALINFO_ITEMS_PUSH1     155
# define CMP_F_CMP_PKIMESSAGE_GENM_ITEMS_PUSH1            156
# define CMP_F_CMP_PKIMESSAGE_GENM_ITEM_PUSH0             157
# define CMP_F_CMP_PKIMESSAGE_HTTP_PERFORM                158
# define CMP_F_CMP_PKIMESSAGE_POLLRESPONSE_GET0           159
# define CMP_F_CMP_PKIMESSAGE_PROTECT                     160
# define CMP_F_CMP_PKISTATUSINFO_PKISTATUS_GET            161
# define CMP_F_CMP_PKISTATUSINFO_PKISTATUS_GET_STRING     162
# define CMP_F_CMP_POLLREQ_NEW                            163
# define CMP_F_CMP_REVREPCONTENT_PKISTATUSINFO_GET        164
# define CMP_F_CMP_RR_NEW                                 165
# define CMP_F_CMP_VALIDATE_CERT_PATH                     166
# define CMP_F_CMP_VALIDATE_MSG                           167
# define CMP_F_CMP_VERIFY_SIGNATURE                       168
# define CMP_F_EXCHANGE_CERTCONF                          169
# define CMP_F_EXCHANGE_ERROR                             170
# define CMP_F_FIND_SRVCERT                               175
# define CMP_F_GET_CERT_STATUS                            171
# define CMP_F_GET_SRVCERT                                174
# define CMP_F_POLLFORRESPONSE                            172
# define CMP_F_SET_SRVCERT                                173
# define CMP_F_CMP_PKIMESSAGE_CHECK_RECEIVED              176
# define CMP_F_CMP_VERIFY_PBMAC                           177
# define CMP_F_CMP_ASN1_OCTET_STRING_SET1                 178
# define CMP_F_SEND_RECEIVE_CHECK                         179

/*
 * CMP reason codes.
 */
# define CMP_R_ALGORITHM_NOT_SUPPORTED                    100
# define CMP_R_CERTIFICATE_NOT_ACCEPTED                   101
# define CMP_R_CERTIFICATE_NOT_FOUND                      102
# define CMP_R_CERTRESPONSE_NOT_FOUND                     103
# define CMP_R_CERT_AND_KEY_DO_NOT_MATCH                  104
# define CMP_R_CONNECT_TIMEOUT                            105
# define CMP_R_CP_NOT_RECEIVED                            106
# define CMP_R_ENCOUNTERED_KEYUPDATEWARNING               107
# define CMP_R_ENCOUNTERED_UNSUPPORTED_PKISTATUS          108
# define CMP_R_ENCOUNTERED_WAITING                        109
# define CMP_R_ERROR_CALCULATING_PROTECTION               110
# define CMP_R_ERROR_CONNECTING                           175
# define CMP_R_ERROR_CREATING_CERTCONF                    111
# define CMP_R_ERROR_CREATING_CR                          112
# define CMP_R_ERROR_CREATING_ERROR                       113
# define CMP_R_ERROR_CREATING_GENM                        114
# define CMP_R_ERROR_CREATING_IR                          115
# define CMP_R_ERROR_CREATING_KUR                         116
# define CMP_R_ERROR_CREATING_P10CR                       117
# define CMP_R_ERROR_CREATING_POLLREQ                     118
# define CMP_R_ERROR_CREATING_RR                          119
# define CMP_R_ERROR_DECODING_CERTIFICATE                 120
# define CMP_R_ERROR_DECODING_MESSAGE                     121
# define CMP_R_ERROR_DECRYPTING_CERTIFICATE               122
# define CMP_R_ERROR_DECRYPTING_ENCCERT                   123
# define CMP_R_ERROR_DECRYPTING_KEY                       124
# define CMP_R_ERROR_DECRYPTING_SYMMETRIC_KEY             125

#endif
