/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2018 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_CRMFERR_H
# define HEADER_CRMFERR_H

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_CRMF

#  ifdef  __cplusplus
extern "C"
#  endif
int ERR_load_CRMF_strings(void);

/*
 * CRMF function codes.
 */

/*
 * CRMF reason codes.
 */

# endif
#endif
