=pod

=head1 NAME

 CMP_doInitialRequestSeq,
 CMP_doKeyUpdateRequestSeq,
 CMP_doCertificateRequestSeq,
 CMP_doPKCS10CertificationRequestSeq,
 CMP_doGeneralMessageSeq,
 CMP_doRevocationRequestSeq

=head1 SYNOPSIS

 #include <openssl/cmp.h>

 X509 *CMP_doInitialRequestSeq(CMP_CTX *ctx);
 X509 *CMP_doKeyUpdateRequestSeq(CMP_CTX *ctx);
 X509 *CMP_doCertificateRequestSeq(CMP_CTX *ctx);
 X509 *CMP_doPKCS10CertificationRequestSeq(CMP_CTX *ctx);
 STACK_OF(CMP_INFOTYPEANDVALUE) *CMP_doGeneralMessageSeq(CMP_CTX *ctx;
 int CMP_doRevocationRequestSeq(CMP_CTX *ctx);

=head1 DESCRIPTION

This is the API for doing CMP (Certificate Management Protocol)  client-server
message sequences using with OpenSSL. The default conveying protocol is HTTP.

CMP_doInitialRequestSeq() does the transaction which obtains an initial certificate
from the CA. A populated CMP_CTX structure has to be given as argument.

CMP_doKeyUpdateRequestSeq() does the transaction which obtains an updated certificate
from the CA. A populated CMP_CTX structure has to be given as argument.

CMP_doCertificateRequestSeq() requests an additional certificate
from the CA. A populated CMP_CTX structure has to be given as argument.

CMP_doPKCS10CertificationRequestSeq(CMP_CTX *ctx) requests in PKCS#10 CSR form
a certificate from the CA. A populated CMP_CTX structure has to be given as argument.

CMP_doGeneralMessageSeq() sends a general message with any ITAVs specified in the
B<ctx>->genm_itavs, and returns the list of B<ITAV>s received in the GenRep.
This can be used, for instance, to poll for the CRL or CA Key Updates.

CMP_doRevocationRequestSeq() requests the revocation of the used certificate via
an revocation request sent to the server.

=head1 NOTES

CMP is defined in RFC 4210 (and CRMF in RFC 4211).

=head1 RETURN VALUES

CMP_doInitialRequestSeq(), CMP_doCertificateRequestSeq(),
CMP_doPKCS10CertificationRequestSeq(), and CMP_doKeyUpdateRequestSeq()
return a pointer the newly obtained X509 certificate on success, NULL on error.

=head1 EXAMPLE

See CMP_CTX for examples on how to prepare the context for these
functions.

=head1 SEE ALSO

CMP_CTX, CMP_http
