=pod

=head1 NAME

 CMP_PKIMESSAGE_http_perform

=head1 SYNOPSIS

 #include <openssl/cmp.h>

 int CMP_PKIMESSAGE_http_perform(const CMP_CTX *ctx, const CMP_PKIMESSAGE *msg, CMP_PKIMESSAGE **out);

=head1 DESCRIPTION

This is the API for creating a BIO for CMP (Certificate Management
Protocol) over HTTP(S) with OpenSSL.

CMP_PKIMESSAGE_http_perform() sends the given pkimessage msg to the CMP server
specified in ctx, and assigns the server's response to *out on success (return 1).

=head1 NOTES

CMP is defined in RFC 4210 (and CRMF in RFC 4211).

=head1 RETURN VALUES

=head1 EXAMPLE

=head1 TODO

=head1 SEE ALSO

CMP_CTX, CMP_session
