/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2018 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include <openssl/crmferr.h>

#ifndef OPENSSL_NO_ERR

static const ERR_STRING_DATA CRMF_str_functs[] = {
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_CREATE_POPO, 0),
     "CRMF_CERTREQMSG_create_popo"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_PUSH0_EXTENSION, 0),
     "CRMF_CERTREQMSG_push0_extension"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_PUSH0_REGCTRL, 0),
     "CRMF_CERTREQMSG_push0_regCtrl"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_PUSH0_REGINFO, 0),
     "CRMF_CERTREQMSG_push0_regInfo"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_SET0_EXTENSIONS, 0),
     "CRMF_CERTREQMSG_set0_extensions"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_SET1_ISSUER, 0),
     "CRMF_CERTREQMSG_set1_issuer"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_SET1_PUBLICKEY, 0),
     "CRMF_CERTREQMSG_set1_publicKey"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_SET1_REGCTRL_OLDCERTID_FROM_CERT, 0),
     "CRMF_CERTREQMSG_set1_regCtrl_oldCertID_from_cert"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_SET1_SUBJECT, 0),
     "CRMF_CERTREQMSG_set1_subject"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_SET_CERTREQID, 0),
     "CRMF_CERTREQMSG_set_certReqId"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_SET_VALIDITY, 0),
     "CRMF_CERTREQMSG_set_validity"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_CERTREQMSG_SET_VERSION2, 0),
     "CRMF_CERTREQMSG_set_version2"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_PASSWORDBASEDMAC_NEW, 0),
     "CRMF_passwordBasedMac_new"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_CRMF_PBMP_NEW, 0), "CRMF_pbmp_new"},
    {ERR_PACK(ERR_LIB_CRMF, CRMF_F_POPOSIGKEY_NEW, 0), "poposigkey_new"},
    {0, NULL}
};

static const ERR_STRING_DATA CRMF_str_reasons[] = {
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_BAD_PBM_ITERATIONCOUNT),
    "bad pbm iterationcount"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_CRMFERROR), "crmferror"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_ERROR), "error"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_FAILURE_OBTAINING_RANDOM),
    "failure obtaining random"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_ITERATIONCOUNT_BELOW_100),
    "iterationcount below 100"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_MALLOC_FAILURE), "malloc failure"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_NULL_ARGUMENT), "null argument"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_SETTING_MAC_ALRGOR_FAILURE),
    "setting mac alrgor failure"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_SETTING_OWF_ALRGOR_FAILURE),
    "setting owf alrgor failure"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_UNSUPPORTED_ALGORITHM),
    "unsupported algorithm"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_UNSUPPORTED_ALG_FOR_POPSIGNINGKEY),
    "unsupported alg for popsigningkey"},
    {ERR_PACK(ERR_LIB_CRMF, 0, CRMF_R_UNSUPPORTED_METHOD_FOR_CREATING_POPO),
    "unsupported method for creating popo"},
    {0, NULL}
};

#endif

int ERR_load_CRMF_strings(void)
{
#ifndef OPENSSL_NO_ERR
    if (ERR_func_error_string(CRMF_str_functs[0].error) == NULL) {
        ERR_load_strings_const(CRMF_str_functs);
        ERR_load_strings_const(CRMF_str_reasons);
    }
#endif
    return 1;
}
